create database if not exists portfolio1;
use portfolio1;

select * from customer_shopping;
alter table customer_shopping rename customers;
select * from customers;


-- Q1. What is the total revenue generated by male vs. female customers?

select 
gender,
sum(purchase_amount) as total_revenue
from customers
group by gender;

# Q.2 Which customers used a discount but still spent more than the average purchase amount ?

select
customer_id,
purchase_amount
from customers
where discount_applied ='Yes'
and purchase_amount >= (select avg(purchase_amount) from customers);

-- Q3. Which are the top 5 products with the highest average review rating?
select 
item_purchased,
round(avg(review_rating),2) as avg_product_rating
from customers
group by item_purchased
order by avg_product_rating desc
limit 6;

-- Q4. Compare the average Purchase Amounts between Standard and Express Shipping.

select 
shipping_type,
round(avg(purchase_amount),2) as avg_purchase_amt
from customers
where shipping_type in ('Express','Standard')
group by shipping_type;

-- Q5. Do subscribed customers spend more? Compare average spend and total revenue between subscriber and non - subscribers

select 
subscription_status,
count(customer_id) as total_customers,
round(avg(purchase_amount),2) as avg_spend,
sum(purchase_amount) as total_revenue
from customers
group by subscription_status;

-- Q6. Which 5 products have the highest percentage of purchases with discounts applied?

select
item_purchased,
round(sum(case when discount_applied='Yes' then 1 else 0 end)/count(item_purchased)*100,2) as pct_disct_prchs
from customers
group by item_purchased
order by pct_disct_prchs desc
limit 5 ;

-- Q7. Segment customers into new, Returning, and Loyal based on their total number of prev purchases , and show the count of each segment

with customer_type as (
SELECT customer_id, previous_purchases,
CASE 
    WHEN previous_purchases = 1 THEN 'New'
    WHEN previous_purchases BETWEEN 2 AND 10 THEN 'Returning'
    ELSE 'Loyal'
    END AS customer_segment
FROM customers)

select customer_segment,count(*) AS "Number of Customers" 
from customer_type 
group by customer_segment;

-- Q8. What are the top 3 most purchased products within each category? 

with item_counts as(
 select
 category,
 item_purchased,
 count(customer_id) as total_orders,
 row_number() over (partition by category order by count(customer_id) desc) as item_rank
from customers
group by category, item_purchased)

select 
category,
item_purchased,
total_orders,
item_rank
from item_counts
where item_rank<=3;

-- Q9. Are customers who are repeat buyers (more than 5 previous purchases) also likely to subscribe?

select 
subscription_status,
count(customer_id) as repeat_buyers
from customers
where previous_purchases > 5
group by subscription_status;

-- Q10. What is the revenue contribution of each age group? 

select
age_group,
sum(purchase_amount) as revenue
from customers
group by age_group;






 
